version: '3'
services:
  game_server:
    build: ./game_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates/certbot/conf:/etc/letsencrypt
      - ./certificates/certbot/www:/var/www/certbot
  room_server:
    build: ./room_server
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - ./certificates/certbot/conf:/etc/letsencrypt
      - ./certificates/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certificates/certbot/conf:/etc/letsencrypt
      - ./certificates/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"