const LOCAL = false;
const HOSTNAME = "c71b400e0fc7.ngrok.io";
var ROOM_SERVER_PORT = 1337;
var ROOM_CAPACITY = 6;

module.exports = 
{
    LOCAL: LOCAL,
    HOSTNAME: HOSTNAME,
    ROOM_SERVER_PORT: ROOM_SERVER_PORT,
    ROOM_CAPACITY: ROOM_CAPACITY,
}